"""
mayini.tinyml.export — Export quantised models to C header files
and a simple ONNX-like JSON format for edge deployment.
"""

from __future__ import annotations

import json
import struct
from pathlib import Path
from typing import Any, Dict, List, Optional


def export_to_c(model: Any, output_file: str = "model.h", fmt: str = "int8") -> Path:
    """Export quantised model weights as a C/C++ header file.

    Parameters
    ----------
    model:
        A Mayini model whose parameters have already been quantised
        (see :class:`~mayini.tinyml.Quantizer`).
    output_file:
        Destination ``.h`` file path.
    fmt:
        C type for weights: ``"int8"`` (default) or ``"float32"``.

    Returns
    -------
    pathlib.Path
        Path to the generated header file.

    Example
    -------
    >>> from mayini.tinyml import Quantizer, export_to_c
    >>> q = Quantizer(model, bits=8).quantize()
    >>> export_to_c(q, "edge_model.h")
    """
    path = Path(output_file)
    lines: List[str] = [
        "// Auto-generated by Mayini Framework (mayini.tinyml.export)",
        "// Do NOT edit manually.",
        "#pragma once",
        "#include <stdint.h>",
        "",
    ]

    import numpy as np

    for name, param in _iter_params(model):
        c_name = name.replace(".", "_").replace("-", "_")
        data = param.data

        if fmt == "int8":
            arr = data.flatten().astype(np.int8)
            c_type = "int8_t"
        else:
            arr = data.flatten().astype(np.float32)
            c_type = "float"

        values = ", ".join(str(v) for v in arr.tolist())
        lines.append(f"// {name}  shape={list(data.shape)}")
        lines.append(
            f"static const {c_type} {c_name}[{arr.size}] = {{{values}}};"
        )
        lines.append("")

    # Minimal inference descriptor struct
    lines += [
        "typedef struct {",
        "    const int8_t* weights;",
        "    float scale;",
        "    int8_t zero_point;",
        "    int rows;",
        "    int cols;",
        "} MayiniLayer;",
        "",
        "// Call mayini_predict(input_ptr, input_len, output_ptr) at runtime",
        "// (implementation generated separately by the C runtime stub)",
    ]

    content = "\n".join(lines)
    path.write_text(content, encoding="utf-8")
    print(f"[tinyml] Exported C header → {path.resolve()}")
    return path


def export_onnx_like(model: Any, output_file: str = "model.json") -> Path:
    """Export model architecture + weights to a portable JSON format.

    This is a lightweight alternative to ONNX for pure-Python edges
    where ``onnx`` is unavailable.

    Parameters
    ----------
    model:
        Mayini model (quantised or float).
    output_file:
        Destination JSON path.

    Returns
    -------
    pathlib.Path
        Path to the generated JSON file.
    """
    import numpy as np

    path = Path(output_file)
    payload: Dict[str, Any] = {
        "format": "mayini-onnx-like/v1",
        "layers": [],
    }

    for name, param in _iter_params(model):
        layer_info = {
            "name": name,
            "shape": list(param.data.shape),
            "dtype": str(param.data.dtype),
            "data": param.data.flatten().tolist(),
        }
        payload["layers"].append(layer_info)

    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    print(f"[tinyml] Exported ONNX-like JSON → {path.resolve()}")
    return path


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _iter_params(model: Any):
    try:
        yield from model.named_parameters()
    except AttributeError:
        for i, p in enumerate(model.parameters()):
            yield (f"param_{i}", p)
