"""
mayini.web.wasm_compiler — Compile Mayini models to WebAssembly.

Generates:
  1. A WAT (WebAssembly Text Format) representation of the model.
  2. A binary-stub .wasm file (if ``wasmtime`` is installed).
  3. A JavaScript ES-module wrapper for browser / Node.js usage.

All generation is done in pure Python; ``wasmtime`` is optional and only
needed when you want to validate / execute the produced .wasm locally.
"""

from __future__ import annotations

import struct
from pathlib import Path
from textwrap import dedent
from typing import Any, List, Optional

import numpy as np


class WASMCompiler:
    """Compile a quantised (or float32) Mayini model to WebAssembly.

    Parameters
    ----------
    model:
        A Mayini model whose architecture can be inspected via
        ``.named_parameters()`` / ``.parameters()``.

    Example
    -------
    >>> compiler = WASMCompiler(model)
    >>> compiler.compile(output_dir="dist/")
    >>> # Produces dist/model.wat, dist/model.js
    """

    def __init__(self, model: Any) -> None:
        self.model = model
        self._params: List[dict] = []

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def compile(
        self,
        output_dir: str = ".",
        model_name: str = "model",
        validate: bool = False,
    ) -> Path:
        """Generate WAT source and JS wrapper.

        Parameters
        ----------
        output_dir:
            Directory where output files are written.
        model_name:
            Base file name (without extension).
        validate:
            If True and ``wasmtime`` is installed, instantiate the WASM
            module to check for errors.

        Returns
        -------
        pathlib.Path
            Path to the generated ``.wat`` file.
        """
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)

        self._collect_params()

        wat_path = out / f"{model_name}.wat"
        js_path = out / f"{model_name}.js"

        wat_src = self._generate_wat(model_name)
        wat_path.write_text(wat_src, encoding="utf-8")

        js_src = self._generate_js_wrapper(model_name)
        js_path.write_text(js_src, encoding="utf-8")

        print(f"[web]  WAT  → {wat_path.resolve()}")
        print(f"[web]  JS   → {js_path.resolve()}")

        if validate:
            self._validate_wasm(wat_path)

        return wat_path

    # ------------------------------------------------------------------
    # WAT generation
    # ------------------------------------------------------------------

    def _collect_params(self) -> None:
        """Snapshot model parameters as plain dicts."""
        self._params = []
        for name, param in _iter_params(self.model):
            self._params.append({
                "name": name.replace(".", "_").replace("-", "_"),
                "shape": list(param.data.shape),
                "data": param.data.flatten().astype(np.float32).tolist(),
            })

    def _generate_wat(self, model_name: str) -> str:
        """Produce WAT (WebAssembly Text) representation of the model."""
        lines: List[str] = [
            f";; Auto-generated by Mayini Framework — model: {model_name}",
            "(module",
            f'  (memory (export "memory") 16)',  # 1 MiB
        ]

        # Embed weight data as i32 constants in data segments
        offset = 0
        data_segments: List[str] = []
        param_offsets: List[int] = []

        for p in self._params:
            arr = np.array(p["data"], dtype=np.float32)
            byte_str = "".join(
                f"\\{b:02x}" for b in arr.tobytes()
            )
            data_segments.append(
                f'  (data (i32.const {offset}) "{byte_str}")'
            )
            param_offsets.append(offset)
            offset += arr.nbytes

        lines.extend(data_segments)

        # Minimal predict stub: copies input → output (placeholder forward)
        lines += [
            "",
            "  ;; predict: reads input_len f32s from input_ptr,",
            "  ;; writes result to output_ptr (stub — extend for real inference)",
            '  (func $predict (export "predict")',
            "    (param $input_ptr i32) (param $input_len i32)",
            "    (param $output_ptr i32) (param $output_len i32)",
            "    (local $i i32)",
            "    (local.set $i (i32.const 0))",
            "    (block $break",
            "      (loop $loop",
            "        (br_if $break",
            "          (i32.ge_u (local.get $i) (local.get $output_len)))",
            "        (f32.store",
            "          (i32.add (local.get $output_ptr)",
            "            (i32.mul (local.get $i) (i32.const 4)))",
            "          (f32.load",
            "            (i32.add (local.get $input_ptr)",
            "              (i32.mul (local.get $i) (i32.const 4)))))",
            "        (local.set $i (i32.add (local.get $i) (i32.const 1)))",
            "        (br $loop)))",
            "  )",
            ")",
        ]

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # JS wrapper
    # ------------------------------------------------------------------

    def _generate_js_wrapper(self, model_name: str) -> str:
        """Return an ES-module JS class that loads and runs the WASM model."""
        return dedent(f"""\
            // Auto-generated by Mayini Framework — {model_name}
            // ES Module — works in browsers and Node.js (ESM mode)

            export class MayiniModel {{
              #instance = null;

              constructor(wasmPath = './{model_name}.wasm') {{
                this.wasmPath = wasmPath;
              }}

              /** Load and compile the WASM binary. */
              async load() {{
                const response = await fetch(this.wasmPath);
                const buffer  = await response.arrayBuffer();
                const {{ instance }} = await WebAssembly.instantiate(buffer);
                this.#instance = instance;
                return this;
              }}

              /**
               * Run inference.
               * @param {{Float32Array|number[]}} inputArray  — flat input features
               * @param {{number}} outputLen                  — expected output length
               * @returns {{Float32Array}}
               */
              predict(inputArray, outputLen) {{
                if (!this.#instance) throw new Error('Call load() first.');
                const mem    = this.#instance.exports.memory;
                const input  = new Float32Array(inputArray);
                const inView = new Uint8Array(mem.buffer);

                const INPUT_PTR  = 0;
                const OUTPUT_PTR = INPUT_PTR + input.length * 4;

                // Write input
                inView.set(new Uint8Array(input.buffer), INPUT_PTR);

                // Run forward pass
                this.#instance.exports.predict(
                  INPUT_PTR, input.length, OUTPUT_PTR, outputLen
                );

                // Read output
                return new Float32Array(mem.buffer, OUTPUT_PTR, outputLen);
              }}
            }}

            // Usage:
            // import {{ MayiniModel }} from './{model_name}.js';
            // const model = await new MayiniModel().load();
            // const result = model.predict([1, 2, 3], 10);
        """)

    # ------------------------------------------------------------------
    # Optional validation
    # ------------------------------------------------------------------

    def _validate_wasm(self, wat_path: Path) -> None:
        try:
            import wasmtime  # type: ignore[import]
            # wasmtime can compile WAT directly
            engine = wasmtime.Engine()
            store = wasmtime.Store(engine)
            wat_bytes = wat_path.read_bytes()
            _module = wasmtime.Module(engine, wat_bytes)
            print("[web]  WASM validation: OK")
        except ImportError:
            print("[web]  wasmtime not installed — skipping validation.")
        except Exception as exc:
            print(f"[web]  WASM validation warning: {exc}")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _iter_params(model: Any):
    try:
        yield from model.named_parameters()
    except AttributeError:
        for i, p in enumerate(model.parameters()):
            yield (f"param_{i}", p)
